query_principal = """
    SELECT 
    ad_group.id,
    ad_group.name,
    ad_group.campaign,
    ad_group.type,
    segments.date,
    segments.hour,
    metrics.active_view_cpm,
    metrics.active_view_ctr,
    metrics.active_view_impressions,
    metrics.active_view_measurability,
    metrics.active_view_measurable_cost_micros,
    metrics.active_view_measurable_impressions,
    metrics.average_cost,
    metrics.average_cpc,
    metrics.average_cpe,
    metrics.average_cpm,
    metrics.average_cpv,
    metrics.clicks,
    metrics.content_impression_share,
    metrics.conversions,
    metrics.ctr,
    metrics.engagement_rate,
    metrics.engagements,
    metrics.impressions,
    metrics.interaction_event_types,
    metrics.interaction_rate,
    metrics.interactions,
    campaign.campaign_group,
    campaign.id,
    campaign.manual_cpa,
    campaign.manual_cpm,
    campaign.manual_cpv,
    campaign.name,
    campaign.status,
    customer.id,
    customer.currency_code,
    customer.descriptive_name,
    customer.status,
    customer.time_zone
    FROM ad_group
    WHERE segments.date BETWEEN '{start_date}' AND '{end_date}'
    ORDER BY segments.date DESC
"""